name: Bug report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the report. Please include concrete repro details.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug.
      placeholder: "When I run ..., I see ..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run ...
        2. Configure ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "Expected ..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/output
      description: Remove secrets before posting.
      render: shell

  - type: dropdown
    id: area
    attributes:
      label: Affected area
      options:
        - CLI run loop
        - Permissions/policy
        - Tool runtime
        - MCP integration
        - Daemon API
        - Release/publish automation
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version/commit
      placeholder: "v0.1.0 or commit sha"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: "OS, Bun version, install method"

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues first
          required: true
        - label: I removed secrets from logs
          required: true
